#!/bin/bash
#echo "Building the hello.cgi C++ CGI Program"
#g++ hello.cpp -o hello.cgi

#echo "Building the getLED.cgi C++ CGI Program"
#g++ getLED.cpp LED.cpp -o getLED.cgi -lcgicc

#echo "Building the postLED.cgi C++ CGI Program"
#g++ postLED.cpp LED.cpp -o postLED.cgi -lcgicc

echo "Building the postCamera.cgi C++ CGI Program"
g++ postCamera.cpp /root/camera/clientserver/network/SocketClient.cpp -o postCamera.cgi -lcgicc -pthread

#echo "Building the music.cgi C++ CGI Program"
#g++ music.cpp -o music.cgi -lcgicc
