#!/bin/bash
echo "Copying the cgi files to the /usr/lib/cgi-bin/"
#sudo cp *.cgi /usr/lib/cgi-bin/
#sudo chmod +s /usr/lib/cgi-bin/getLED.cgi
#sudo chmod +s /usr/lib/cgi-bin/postLED.cgi
cp *.cgi /usr/lib/cgi-bin/
chmod +s /usr/lib/cgi-bin/getLED.cgi
chmod +s /usr/lib/cgi-bin/postLED.cgi
chmod +s /usr/lib/cgi-bin/postCamera.cgi
chmod +s /usr/lib/cgi-bin/music.cgi
